gdjs.startCode = {};
gdjs.startCode.localVariables = [];
gdjs.startCode.GDBigGreenTree2Objects1= [];
gdjs.startCode.GDBigGreenTree2Objects2= [];
gdjs.startCode.GDBigGreenTree2Objects3= [];
gdjs.startCode.GDBigGreenTree1Objects1= [];
gdjs.startCode.GDBigGreenTree1Objects2= [];
gdjs.startCode.GDBigGreenTree1Objects3= [];
gdjs.startCode.GDGreenLeavesObjects1= [];
gdjs.startCode.GDGreenLeavesObjects2= [];
gdjs.startCode.GDGreenLeavesObjects3= [];
gdjs.startCode.GDBigGreenTree4Objects1= [];
gdjs.startCode.GDBigGreenTree4Objects2= [];
gdjs.startCode.GDBigGreenTree4Objects3= [];
gdjs.startCode.GDBigGreenTree3Objects1= [];
gdjs.startCode.GDBigGreenTree3Objects2= [];
gdjs.startCode.GDBigGreenTree3Objects3= [];
gdjs.startCode.GDOrangeLeavesObjects1= [];
gdjs.startCode.GDOrangeLeavesObjects2= [];
gdjs.startCode.GDOrangeLeavesObjects3= [];
gdjs.startCode.GDBigGreenTree6Objects1= [];
gdjs.startCode.GDBigGreenTree6Objects2= [];
gdjs.startCode.GDBigGreenTree6Objects3= [];
gdjs.startCode.GDBigGreenTree5Objects1= [];
gdjs.startCode.GDBigGreenTree5Objects2= [];
gdjs.startCode.GDBigGreenTree5Objects3= [];
gdjs.startCode.GDBigGreenTree8Objects1= [];
gdjs.startCode.GDBigGreenTree8Objects2= [];
gdjs.startCode.GDBigGreenTree8Objects3= [];
gdjs.startCode.GDBigGreenTree7Objects1= [];
gdjs.startCode.GDBigGreenTree7Objects2= [];
gdjs.startCode.GDBigGreenTree7Objects3= [];
gdjs.startCode.GDBigOrangeTree2Objects1= [];
gdjs.startCode.GDBigOrangeTree2Objects2= [];
gdjs.startCode.GDBigOrangeTree2Objects3= [];
gdjs.startCode.GDBigOrangeTree1Objects1= [];
gdjs.startCode.GDBigOrangeTree1Objects2= [];
gdjs.startCode.GDBigOrangeTree1Objects3= [];
gdjs.startCode.GDBigOrangeTree3Objects1= [];
gdjs.startCode.GDBigOrangeTree3Objects2= [];
gdjs.startCode.GDBigOrangeTree3Objects3= [];
gdjs.startCode.GDBigOrangeTree4Objects1= [];
gdjs.startCode.GDBigOrangeTree4Objects2= [];
gdjs.startCode.GDBigOrangeTree4Objects3= [];
gdjs.startCode.GDBigTreeWithSnow1Objects1= [];
gdjs.startCode.GDBigTreeWithSnow1Objects2= [];
gdjs.startCode.GDBigTreeWithSnow1Objects3= [];
gdjs.startCode.GDBigOrangeTree5Objects1= [];
gdjs.startCode.GDBigOrangeTree5Objects2= [];
gdjs.startCode.GDBigOrangeTree5Objects3= [];
gdjs.startCode.GDBigOrangeTree6Objects1= [];
gdjs.startCode.GDBigOrangeTree6Objects2= [];
gdjs.startCode.GDBigOrangeTree6Objects3= [];
gdjs.startCode.GDBigTreeWithSnow2Objects1= [];
gdjs.startCode.GDBigTreeWithSnow2Objects2= [];
gdjs.startCode.GDBigTreeWithSnow2Objects3= [];
gdjs.startCode.GDBigTreeWithSnow3Objects1= [];
gdjs.startCode.GDBigTreeWithSnow3Objects2= [];
gdjs.startCode.GDBigTreeWithSnow3Objects3= [];
gdjs.startCode.GDBlueFlowerObjects1= [];
gdjs.startCode.GDBlueFlowerObjects2= [];
gdjs.startCode.GDBlueFlowerObjects3= [];
gdjs.startCode.GDGreenBush1Objects1= [];
gdjs.startCode.GDGreenBush1Objects2= [];
gdjs.startCode.GDGreenBush1Objects3= [];
gdjs.startCode.GDGreenBush2Objects1= [];
gdjs.startCode.GDGreenBush2Objects2= [];
gdjs.startCode.GDGreenBush2Objects3= [];
gdjs.startCode.GDBlueSmallPlantObjects1= [];
gdjs.startCode.GDBlueSmallPlantObjects2= [];
gdjs.startCode.GDBlueSmallPlantObjects3= [];
gdjs.startCode.GDGreenBush3Objects1= [];
gdjs.startCode.GDGreenBush3Objects2= [];
gdjs.startCode.GDGreenBush3Objects3= [];
gdjs.startCode.GDGreenBush4Objects1= [];
gdjs.startCode.GDGreenBush4Objects2= [];
gdjs.startCode.GDGreenBush4Objects3= [];
gdjs.startCode.GDGreenTreeLeaves1Objects1= [];
gdjs.startCode.GDGreenTreeLeaves1Objects2= [];
gdjs.startCode.GDGreenTreeLeaves1Objects3= [];
gdjs.startCode.GDGreenTreeLeaves3Objects1= [];
gdjs.startCode.GDGreenTreeLeaves3Objects2= [];
gdjs.startCode.GDGreenTreeLeaves3Objects3= [];
gdjs.startCode.GDGreenTreeLeaves5Objects1= [];
gdjs.startCode.GDGreenTreeLeaves5Objects2= [];
gdjs.startCode.GDGreenTreeLeaves5Objects3= [];
gdjs.startCode.GDGreenTreeLeaves2Objects1= [];
gdjs.startCode.GDGreenTreeLeaves2Objects2= [];
gdjs.startCode.GDGreenTreeLeaves2Objects3= [];
gdjs.startCode.GDGreenTreeLeaves4Objects1= [];
gdjs.startCode.GDGreenTreeLeaves4Objects2= [];
gdjs.startCode.GDGreenTreeLeaves4Objects3= [];
gdjs.startCode.GDGreenTreeLeaves6Objects1= [];
gdjs.startCode.GDGreenTreeLeaves6Objects2= [];
gdjs.startCode.GDGreenTreeLeaves6Objects3= [];
gdjs.startCode.GDGreenTreeLeaves7Objects1= [];
gdjs.startCode.GDGreenTreeLeaves7Objects2= [];
gdjs.startCode.GDGreenTreeLeaves7Objects3= [];
gdjs.startCode.GDOrangeTreeLeaves1Objects1= [];
gdjs.startCode.GDOrangeTreeLeaves1Objects2= [];
gdjs.startCode.GDOrangeTreeLeaves1Objects3= [];
gdjs.startCode.GDOrangeTreeLeaves2Objects1= [];
gdjs.startCode.GDOrangeTreeLeaves2Objects2= [];
gdjs.startCode.GDOrangeTreeLeaves2Objects3= [];
gdjs.startCode.GDOrangeTreeLeaves3Objects1= [];
gdjs.startCode.GDOrangeTreeLeaves3Objects2= [];
gdjs.startCode.GDOrangeTreeLeaves3Objects3= [];
gdjs.startCode.GDOrangeTreeLeaves4Objects1= [];
gdjs.startCode.GDOrangeTreeLeaves4Objects2= [];
gdjs.startCode.GDOrangeTreeLeaves4Objects3= [];
gdjs.startCode.GDOrangeTreeLeaves6Objects1= [];
gdjs.startCode.GDOrangeTreeLeaves6Objects2= [];
gdjs.startCode.GDOrangeTreeLeaves6Objects3= [];
gdjs.startCode.GDOrangeTreeLeaves5Objects1= [];
gdjs.startCode.GDOrangeTreeLeaves5Objects2= [];
gdjs.startCode.GDOrangeTreeLeaves5Objects3= [];
gdjs.startCode.GDRedFlowerObjects1= [];
gdjs.startCode.GDRedFlowerObjects2= [];
gdjs.startCode.GDRedFlowerObjects3= [];
gdjs.startCode.GDPurpleSmallPlantObjects1= [];
gdjs.startCode.GDPurpleSmallPlantObjects2= [];
gdjs.startCode.GDPurpleSmallPlantObjects3= [];
gdjs.startCode.GDSmallGrassObjects1= [];
gdjs.startCode.GDSmallGrassObjects2= [];
gdjs.startCode.GDSmallGrassObjects3= [];
gdjs.startCode.GDSmallPlant1Objects1= [];
gdjs.startCode.GDSmallPlant1Objects2= [];
gdjs.startCode.GDSmallPlant1Objects3= [];
gdjs.startCode.GDTrunk1Objects1= [];
gdjs.startCode.GDTrunk1Objects2= [];
gdjs.startCode.GDTrunk1Objects3= [];
gdjs.startCode.GDSmallPlant2Objects1= [];
gdjs.startCode.GDSmallPlant2Objects2= [];
gdjs.startCode.GDSmallPlant2Objects3= [];
gdjs.startCode.GDTrunk4Objects1= [];
gdjs.startCode.GDTrunk4Objects2= [];
gdjs.startCode.GDTrunk4Objects3= [];
gdjs.startCode.GDTinyGrassObjects1= [];
gdjs.startCode.GDTinyGrassObjects2= [];
gdjs.startCode.GDTinyGrassObjects3= [];
gdjs.startCode.GDTrunk2Objects1= [];
gdjs.startCode.GDTrunk2Objects2= [];
gdjs.startCode.GDTrunk2Objects3= [];
gdjs.startCode.GDTrunk3Objects1= [];
gdjs.startCode.GDTrunk3Objects2= [];
gdjs.startCode.GDTrunk3Objects3= [];
gdjs.startCode.GDWhiteTree1Objects1= [];
gdjs.startCode.GDWhiteTree1Objects2= [];
gdjs.startCode.GDWhiteTree1Objects3= [];
gdjs.startCode.GDWhiteTree2Objects1= [];
gdjs.startCode.GDWhiteTree2Objects2= [];
gdjs.startCode.GDWhiteTree2Objects3= [];
gdjs.startCode.GDWhiteTree3Objects1= [];
gdjs.startCode.GDWhiteTree3Objects2= [];
gdjs.startCode.GDWhiteTree3Objects3= [];
gdjs.startCode.GDWhiteTrunk3Objects1= [];
gdjs.startCode.GDWhiteTrunk3Objects2= [];
gdjs.startCode.GDWhiteTrunk3Objects3= [];
gdjs.startCode.GDWhiteTrunk4Objects1= [];
gdjs.startCode.GDWhiteTrunk4Objects2= [];
gdjs.startCode.GDWhiteTrunk4Objects3= [];
gdjs.startCode.GDWhiteTrunk2Objects1= [];
gdjs.startCode.GDWhiteTrunk2Objects2= [];
gdjs.startCode.GDWhiteTrunk2Objects3= [];
gdjs.startCode.GDWhiteTrunkObjects1= [];
gdjs.startCode.GDWhiteTrunkObjects2= [];
gdjs.startCode.GDWhiteTrunkObjects3= [];
gdjs.startCode.GDRock2Objects1= [];
gdjs.startCode.GDRock2Objects2= [];
gdjs.startCode.GDRock2Objects3= [];
gdjs.startCode.GDRock1Objects1= [];
gdjs.startCode.GDRock1Objects2= [];
gdjs.startCode.GDRock1Objects3= [];
gdjs.startCode.GDRock4Objects1= [];
gdjs.startCode.GDRock4Objects2= [];
gdjs.startCode.GDRock4Objects3= [];
gdjs.startCode.GDRock3Objects1= [];
gdjs.startCode.GDRock3Objects2= [];
gdjs.startCode.GDRock3Objects3= [];
gdjs.startCode.GDRock5Objects1= [];
gdjs.startCode.GDRock5Objects2= [];
gdjs.startCode.GDRock5Objects3= [];
gdjs.startCode.GDRock6Objects1= [];
gdjs.startCode.GDRock6Objects2= [];
gdjs.startCode.GDRock6Objects3= [];
gdjs.startCode.GDRockWithGrass2Objects1= [];
gdjs.startCode.GDRockWithGrass2Objects2= [];
gdjs.startCode.GDRockWithGrass2Objects3= [];
gdjs.startCode.GDRockWithGrass3Objects1= [];
gdjs.startCode.GDRockWithGrass3Objects2= [];
gdjs.startCode.GDRockWithGrass3Objects3= [];
gdjs.startCode.GDRockWithGrassObjects1= [];
gdjs.startCode.GDRockWithGrassObjects2= [];
gdjs.startCode.GDRockWithGrassObjects3= [];
gdjs.startCode.GDVikingBoatObjects1= [];
gdjs.startCode.GDVikingBoatObjects2= [];
gdjs.startCode.GDVikingBoatObjects3= [];
gdjs.startCode.GDLifeboatObjects1= [];
gdjs.startCode.GDLifeboatObjects2= [];
gdjs.startCode.GDLifeboatObjects3= [];
gdjs.startCode.GDCruiseShipObjects1= [];
gdjs.startCode.GDCruiseShipObjects2= [];
gdjs.startCode.GDCruiseShipObjects3= [];
gdjs.startCode.GDSailShipObjects1= [];
gdjs.startCode.GDSailShipObjects2= [];
gdjs.startCode.GDSailShipObjects3= [];
gdjs.startCode.GDBoatWSailObjects1= [];
gdjs.startCode.GDBoatWSailObjects2= [];
gdjs.startCode.GDBoatWSailObjects3= [];
gdjs.startCode.GDBoatObjects1= [];
gdjs.startCode.GDBoatObjects2= [];
gdjs.startCode.GDBoatObjects3= [];
gdjs.startCode.GDNewSprite2Objects1= [];
gdjs.startCode.GDNewSprite2Objects2= [];
gdjs.startCode.GDNewSprite2Objects3= [];
gdjs.startCode.GD_9595029Objects1= [];
gdjs.startCode.GD_9595029Objects2= [];
gdjs.startCode.GD_9595029Objects3= [];
gdjs.startCode.GD_9595030Objects1= [];
gdjs.startCode.GD_9595030Objects2= [];
gdjs.startCode.GD_9595030Objects3= [];
gdjs.startCode.GDStartButtonObjects1= [];
gdjs.startCode.GDStartButtonObjects2= [];
gdjs.startCode.GDStartButtonObjects3= [];


gdjs.startCode.mapOfGDgdjs_9546startCode_9546GDStartButtonObjects1Objects = Hashtable.newFrom({"StartButton": gdjs.startCode.GDStartButtonObjects1});
gdjs.startCode.asyncCallback15362796 = function (runtimeScene, asyncObjectsList) {
asyncObjectsList.restoreLocalVariablesContainers(gdjs.startCode.localVariables);
{gdjs.evtTools.runtimeScene.pushScene(runtimeScene, "to");
}gdjs.startCode.localVariables.length = 0;
}
gdjs.startCode.eventsList0 = function(runtimeScene, asyncObjectsList) {

{


{
const parentAsyncObjectsList = asyncObjectsList;
{
const asyncObjectsList = gdjs.LongLivedObjectsList.from(parentAsyncObjectsList);
asyncObjectsList.backupLocalVariablesContainers(gdjs.startCode.localVariables);
runtimeScene.getAsyncTasksManager().addTask(gdjs.evtTools.runtimeScene.wait(10.56), (runtimeScene) => (gdjs.startCode.asyncCallback15362796(runtimeScene, asyncObjectsList)));
}
}

}


};gdjs.startCode.asyncCallback15362324 = function (runtimeScene, asyncObjectsList) {
asyncObjectsList.restoreLocalVariablesContainers(gdjs.startCode.localVariables);
gdjs.copyArray(asyncObjectsList.getObjects("StartButton"), gdjs.startCode.GDStartButtonObjects2);

{for(var i = 0, len = gdjs.startCode.GDStartButtonObjects2.length ;i < len;++i) {
    gdjs.startCode.GDStartButtonObjects2[i].getBehavior("Scale").setScale(gdjs.startCode.GDStartButtonObjects2[i].getBehavior("Scale").getScale() + (20));
}
}{gdjs.evtTools.sound.playSound(runtimeScene, "b3ea98d934998faa8211a5baf54b4334d0b9ec359ff8c4f2807d900d6222e5c3_Painting Room.aac", false, 50, 1.35);
}
{ //Subevents
gdjs.startCode.eventsList0(runtimeScene, asyncObjectsList);} //End of subevents
gdjs.startCode.localVariables.length = 0;
}
gdjs.startCode.eventsList1 = function(runtimeScene) {

{


{
{
const asyncObjectsList = new gdjs.LongLivedObjectsList();
asyncObjectsList.backupLocalVariablesContainers(gdjs.startCode.localVariables);
for (const obj of gdjs.startCode.GDStartButtonObjects1) asyncObjectsList.addObject("StartButton", obj);
runtimeScene.getAsyncTasksManager().addTask(gdjs.evtTools.runtimeScene.wait(1), (runtimeScene) => (gdjs.startCode.asyncCallback15362324(runtimeScene, asyncObjectsList)));
}
}

}


};gdjs.startCode.eventsList2 = function(runtimeScene) {

{

gdjs.copyArray(runtimeScene.getObjects("StartButton"), gdjs.startCode.GDStartButtonObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.input.cursorOnObject(gdjs.startCode.mapOfGDgdjs_9546startCode_9546GDStartButtonObjects1Objects, runtimeScene, true, false);
if (isConditionTrue_0) {
isConditionTrue_0 = false;
{isConditionTrue_0 = runtimeScene.getOnceTriggers().triggerOnce(15362252);
}
}
if (isConditionTrue_0) {

{ //Subevents
gdjs.startCode.eventsList1(runtimeScene);} //End of subevents
}

}


{


let isConditionTrue_0 = false;
{
}

}


};

gdjs.startCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.startCode.GDBigGreenTree2Objects1.length = 0;
gdjs.startCode.GDBigGreenTree2Objects2.length = 0;
gdjs.startCode.GDBigGreenTree2Objects3.length = 0;
gdjs.startCode.GDBigGreenTree1Objects1.length = 0;
gdjs.startCode.GDBigGreenTree1Objects2.length = 0;
gdjs.startCode.GDBigGreenTree1Objects3.length = 0;
gdjs.startCode.GDGreenLeavesObjects1.length = 0;
gdjs.startCode.GDGreenLeavesObjects2.length = 0;
gdjs.startCode.GDGreenLeavesObjects3.length = 0;
gdjs.startCode.GDBigGreenTree4Objects1.length = 0;
gdjs.startCode.GDBigGreenTree4Objects2.length = 0;
gdjs.startCode.GDBigGreenTree4Objects3.length = 0;
gdjs.startCode.GDBigGreenTree3Objects1.length = 0;
gdjs.startCode.GDBigGreenTree3Objects2.length = 0;
gdjs.startCode.GDBigGreenTree3Objects3.length = 0;
gdjs.startCode.GDOrangeLeavesObjects1.length = 0;
gdjs.startCode.GDOrangeLeavesObjects2.length = 0;
gdjs.startCode.GDOrangeLeavesObjects3.length = 0;
gdjs.startCode.GDBigGreenTree6Objects1.length = 0;
gdjs.startCode.GDBigGreenTree6Objects2.length = 0;
gdjs.startCode.GDBigGreenTree6Objects3.length = 0;
gdjs.startCode.GDBigGreenTree5Objects1.length = 0;
gdjs.startCode.GDBigGreenTree5Objects2.length = 0;
gdjs.startCode.GDBigGreenTree5Objects3.length = 0;
gdjs.startCode.GDBigGreenTree8Objects1.length = 0;
gdjs.startCode.GDBigGreenTree8Objects2.length = 0;
gdjs.startCode.GDBigGreenTree8Objects3.length = 0;
gdjs.startCode.GDBigGreenTree7Objects1.length = 0;
gdjs.startCode.GDBigGreenTree7Objects2.length = 0;
gdjs.startCode.GDBigGreenTree7Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree2Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree2Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree2Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree1Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree1Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree1Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree3Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree3Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree3Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree4Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree4Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree4Objects3.length = 0;
gdjs.startCode.GDBigTreeWithSnow1Objects1.length = 0;
gdjs.startCode.GDBigTreeWithSnow1Objects2.length = 0;
gdjs.startCode.GDBigTreeWithSnow1Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree5Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree5Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree5Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree6Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree6Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree6Objects3.length = 0;
gdjs.startCode.GDBigTreeWithSnow2Objects1.length = 0;
gdjs.startCode.GDBigTreeWithSnow2Objects2.length = 0;
gdjs.startCode.GDBigTreeWithSnow2Objects3.length = 0;
gdjs.startCode.GDBigTreeWithSnow3Objects1.length = 0;
gdjs.startCode.GDBigTreeWithSnow3Objects2.length = 0;
gdjs.startCode.GDBigTreeWithSnow3Objects3.length = 0;
gdjs.startCode.GDBlueFlowerObjects1.length = 0;
gdjs.startCode.GDBlueFlowerObjects2.length = 0;
gdjs.startCode.GDBlueFlowerObjects3.length = 0;
gdjs.startCode.GDGreenBush1Objects1.length = 0;
gdjs.startCode.GDGreenBush1Objects2.length = 0;
gdjs.startCode.GDGreenBush1Objects3.length = 0;
gdjs.startCode.GDGreenBush2Objects1.length = 0;
gdjs.startCode.GDGreenBush2Objects2.length = 0;
gdjs.startCode.GDGreenBush2Objects3.length = 0;
gdjs.startCode.GDBlueSmallPlantObjects1.length = 0;
gdjs.startCode.GDBlueSmallPlantObjects2.length = 0;
gdjs.startCode.GDBlueSmallPlantObjects3.length = 0;
gdjs.startCode.GDGreenBush3Objects1.length = 0;
gdjs.startCode.GDGreenBush3Objects2.length = 0;
gdjs.startCode.GDGreenBush3Objects3.length = 0;
gdjs.startCode.GDGreenBush4Objects1.length = 0;
gdjs.startCode.GDGreenBush4Objects2.length = 0;
gdjs.startCode.GDGreenBush4Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves1Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves1Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves1Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves3Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves3Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves3Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves5Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves5Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves5Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves2Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves2Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves2Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves4Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves4Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves4Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves6Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves6Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves6Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves7Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves7Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves7Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves1Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves1Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves1Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves2Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves2Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves2Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves3Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves3Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves3Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves4Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves4Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves4Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves6Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves6Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves6Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves5Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves5Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves5Objects3.length = 0;
gdjs.startCode.GDRedFlowerObjects1.length = 0;
gdjs.startCode.GDRedFlowerObjects2.length = 0;
gdjs.startCode.GDRedFlowerObjects3.length = 0;
gdjs.startCode.GDPurpleSmallPlantObjects1.length = 0;
gdjs.startCode.GDPurpleSmallPlantObjects2.length = 0;
gdjs.startCode.GDPurpleSmallPlantObjects3.length = 0;
gdjs.startCode.GDSmallGrassObjects1.length = 0;
gdjs.startCode.GDSmallGrassObjects2.length = 0;
gdjs.startCode.GDSmallGrassObjects3.length = 0;
gdjs.startCode.GDSmallPlant1Objects1.length = 0;
gdjs.startCode.GDSmallPlant1Objects2.length = 0;
gdjs.startCode.GDSmallPlant1Objects3.length = 0;
gdjs.startCode.GDTrunk1Objects1.length = 0;
gdjs.startCode.GDTrunk1Objects2.length = 0;
gdjs.startCode.GDTrunk1Objects3.length = 0;
gdjs.startCode.GDSmallPlant2Objects1.length = 0;
gdjs.startCode.GDSmallPlant2Objects2.length = 0;
gdjs.startCode.GDSmallPlant2Objects3.length = 0;
gdjs.startCode.GDTrunk4Objects1.length = 0;
gdjs.startCode.GDTrunk4Objects2.length = 0;
gdjs.startCode.GDTrunk4Objects3.length = 0;
gdjs.startCode.GDTinyGrassObjects1.length = 0;
gdjs.startCode.GDTinyGrassObjects2.length = 0;
gdjs.startCode.GDTinyGrassObjects3.length = 0;
gdjs.startCode.GDTrunk2Objects1.length = 0;
gdjs.startCode.GDTrunk2Objects2.length = 0;
gdjs.startCode.GDTrunk2Objects3.length = 0;
gdjs.startCode.GDTrunk3Objects1.length = 0;
gdjs.startCode.GDTrunk3Objects2.length = 0;
gdjs.startCode.GDTrunk3Objects3.length = 0;
gdjs.startCode.GDWhiteTree1Objects1.length = 0;
gdjs.startCode.GDWhiteTree1Objects2.length = 0;
gdjs.startCode.GDWhiteTree1Objects3.length = 0;
gdjs.startCode.GDWhiteTree2Objects1.length = 0;
gdjs.startCode.GDWhiteTree2Objects2.length = 0;
gdjs.startCode.GDWhiteTree2Objects3.length = 0;
gdjs.startCode.GDWhiteTree3Objects1.length = 0;
gdjs.startCode.GDWhiteTree3Objects2.length = 0;
gdjs.startCode.GDWhiteTree3Objects3.length = 0;
gdjs.startCode.GDWhiteTrunk3Objects1.length = 0;
gdjs.startCode.GDWhiteTrunk3Objects2.length = 0;
gdjs.startCode.GDWhiteTrunk3Objects3.length = 0;
gdjs.startCode.GDWhiteTrunk4Objects1.length = 0;
gdjs.startCode.GDWhiteTrunk4Objects2.length = 0;
gdjs.startCode.GDWhiteTrunk4Objects3.length = 0;
gdjs.startCode.GDWhiteTrunk2Objects1.length = 0;
gdjs.startCode.GDWhiteTrunk2Objects2.length = 0;
gdjs.startCode.GDWhiteTrunk2Objects3.length = 0;
gdjs.startCode.GDWhiteTrunkObjects1.length = 0;
gdjs.startCode.GDWhiteTrunkObjects2.length = 0;
gdjs.startCode.GDWhiteTrunkObjects3.length = 0;
gdjs.startCode.GDRock2Objects1.length = 0;
gdjs.startCode.GDRock2Objects2.length = 0;
gdjs.startCode.GDRock2Objects3.length = 0;
gdjs.startCode.GDRock1Objects1.length = 0;
gdjs.startCode.GDRock1Objects2.length = 0;
gdjs.startCode.GDRock1Objects3.length = 0;
gdjs.startCode.GDRock4Objects1.length = 0;
gdjs.startCode.GDRock4Objects2.length = 0;
gdjs.startCode.GDRock4Objects3.length = 0;
gdjs.startCode.GDRock3Objects1.length = 0;
gdjs.startCode.GDRock3Objects2.length = 0;
gdjs.startCode.GDRock3Objects3.length = 0;
gdjs.startCode.GDRock5Objects1.length = 0;
gdjs.startCode.GDRock5Objects2.length = 0;
gdjs.startCode.GDRock5Objects3.length = 0;
gdjs.startCode.GDRock6Objects1.length = 0;
gdjs.startCode.GDRock6Objects2.length = 0;
gdjs.startCode.GDRock6Objects3.length = 0;
gdjs.startCode.GDRockWithGrass2Objects1.length = 0;
gdjs.startCode.GDRockWithGrass2Objects2.length = 0;
gdjs.startCode.GDRockWithGrass2Objects3.length = 0;
gdjs.startCode.GDRockWithGrass3Objects1.length = 0;
gdjs.startCode.GDRockWithGrass3Objects2.length = 0;
gdjs.startCode.GDRockWithGrass3Objects3.length = 0;
gdjs.startCode.GDRockWithGrassObjects1.length = 0;
gdjs.startCode.GDRockWithGrassObjects2.length = 0;
gdjs.startCode.GDRockWithGrassObjects3.length = 0;
gdjs.startCode.GDVikingBoatObjects1.length = 0;
gdjs.startCode.GDVikingBoatObjects2.length = 0;
gdjs.startCode.GDVikingBoatObjects3.length = 0;
gdjs.startCode.GDLifeboatObjects1.length = 0;
gdjs.startCode.GDLifeboatObjects2.length = 0;
gdjs.startCode.GDLifeboatObjects3.length = 0;
gdjs.startCode.GDCruiseShipObjects1.length = 0;
gdjs.startCode.GDCruiseShipObjects2.length = 0;
gdjs.startCode.GDCruiseShipObjects3.length = 0;
gdjs.startCode.GDSailShipObjects1.length = 0;
gdjs.startCode.GDSailShipObjects2.length = 0;
gdjs.startCode.GDSailShipObjects3.length = 0;
gdjs.startCode.GDBoatWSailObjects1.length = 0;
gdjs.startCode.GDBoatWSailObjects2.length = 0;
gdjs.startCode.GDBoatWSailObjects3.length = 0;
gdjs.startCode.GDBoatObjects1.length = 0;
gdjs.startCode.GDBoatObjects2.length = 0;
gdjs.startCode.GDBoatObjects3.length = 0;
gdjs.startCode.GDNewSprite2Objects1.length = 0;
gdjs.startCode.GDNewSprite2Objects2.length = 0;
gdjs.startCode.GDNewSprite2Objects3.length = 0;
gdjs.startCode.GD_9595029Objects1.length = 0;
gdjs.startCode.GD_9595029Objects2.length = 0;
gdjs.startCode.GD_9595029Objects3.length = 0;
gdjs.startCode.GD_9595030Objects1.length = 0;
gdjs.startCode.GD_9595030Objects2.length = 0;
gdjs.startCode.GD_9595030Objects3.length = 0;
gdjs.startCode.GDStartButtonObjects1.length = 0;
gdjs.startCode.GDStartButtonObjects2.length = 0;
gdjs.startCode.GDStartButtonObjects3.length = 0;

gdjs.startCode.eventsList2(runtimeScene);
gdjs.startCode.GDBigGreenTree2Objects1.length = 0;
gdjs.startCode.GDBigGreenTree2Objects2.length = 0;
gdjs.startCode.GDBigGreenTree2Objects3.length = 0;
gdjs.startCode.GDBigGreenTree1Objects1.length = 0;
gdjs.startCode.GDBigGreenTree1Objects2.length = 0;
gdjs.startCode.GDBigGreenTree1Objects3.length = 0;
gdjs.startCode.GDGreenLeavesObjects1.length = 0;
gdjs.startCode.GDGreenLeavesObjects2.length = 0;
gdjs.startCode.GDGreenLeavesObjects3.length = 0;
gdjs.startCode.GDBigGreenTree4Objects1.length = 0;
gdjs.startCode.GDBigGreenTree4Objects2.length = 0;
gdjs.startCode.GDBigGreenTree4Objects3.length = 0;
gdjs.startCode.GDBigGreenTree3Objects1.length = 0;
gdjs.startCode.GDBigGreenTree3Objects2.length = 0;
gdjs.startCode.GDBigGreenTree3Objects3.length = 0;
gdjs.startCode.GDOrangeLeavesObjects1.length = 0;
gdjs.startCode.GDOrangeLeavesObjects2.length = 0;
gdjs.startCode.GDOrangeLeavesObjects3.length = 0;
gdjs.startCode.GDBigGreenTree6Objects1.length = 0;
gdjs.startCode.GDBigGreenTree6Objects2.length = 0;
gdjs.startCode.GDBigGreenTree6Objects3.length = 0;
gdjs.startCode.GDBigGreenTree5Objects1.length = 0;
gdjs.startCode.GDBigGreenTree5Objects2.length = 0;
gdjs.startCode.GDBigGreenTree5Objects3.length = 0;
gdjs.startCode.GDBigGreenTree8Objects1.length = 0;
gdjs.startCode.GDBigGreenTree8Objects2.length = 0;
gdjs.startCode.GDBigGreenTree8Objects3.length = 0;
gdjs.startCode.GDBigGreenTree7Objects1.length = 0;
gdjs.startCode.GDBigGreenTree7Objects2.length = 0;
gdjs.startCode.GDBigGreenTree7Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree2Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree2Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree2Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree1Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree1Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree1Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree3Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree3Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree3Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree4Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree4Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree4Objects3.length = 0;
gdjs.startCode.GDBigTreeWithSnow1Objects1.length = 0;
gdjs.startCode.GDBigTreeWithSnow1Objects2.length = 0;
gdjs.startCode.GDBigTreeWithSnow1Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree5Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree5Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree5Objects3.length = 0;
gdjs.startCode.GDBigOrangeTree6Objects1.length = 0;
gdjs.startCode.GDBigOrangeTree6Objects2.length = 0;
gdjs.startCode.GDBigOrangeTree6Objects3.length = 0;
gdjs.startCode.GDBigTreeWithSnow2Objects1.length = 0;
gdjs.startCode.GDBigTreeWithSnow2Objects2.length = 0;
gdjs.startCode.GDBigTreeWithSnow2Objects3.length = 0;
gdjs.startCode.GDBigTreeWithSnow3Objects1.length = 0;
gdjs.startCode.GDBigTreeWithSnow3Objects2.length = 0;
gdjs.startCode.GDBigTreeWithSnow3Objects3.length = 0;
gdjs.startCode.GDBlueFlowerObjects1.length = 0;
gdjs.startCode.GDBlueFlowerObjects2.length = 0;
gdjs.startCode.GDBlueFlowerObjects3.length = 0;
gdjs.startCode.GDGreenBush1Objects1.length = 0;
gdjs.startCode.GDGreenBush1Objects2.length = 0;
gdjs.startCode.GDGreenBush1Objects3.length = 0;
gdjs.startCode.GDGreenBush2Objects1.length = 0;
gdjs.startCode.GDGreenBush2Objects2.length = 0;
gdjs.startCode.GDGreenBush2Objects3.length = 0;
gdjs.startCode.GDBlueSmallPlantObjects1.length = 0;
gdjs.startCode.GDBlueSmallPlantObjects2.length = 0;
gdjs.startCode.GDBlueSmallPlantObjects3.length = 0;
gdjs.startCode.GDGreenBush3Objects1.length = 0;
gdjs.startCode.GDGreenBush3Objects2.length = 0;
gdjs.startCode.GDGreenBush3Objects3.length = 0;
gdjs.startCode.GDGreenBush4Objects1.length = 0;
gdjs.startCode.GDGreenBush4Objects2.length = 0;
gdjs.startCode.GDGreenBush4Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves1Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves1Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves1Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves3Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves3Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves3Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves5Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves5Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves5Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves2Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves2Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves2Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves4Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves4Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves4Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves6Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves6Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves6Objects3.length = 0;
gdjs.startCode.GDGreenTreeLeaves7Objects1.length = 0;
gdjs.startCode.GDGreenTreeLeaves7Objects2.length = 0;
gdjs.startCode.GDGreenTreeLeaves7Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves1Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves1Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves1Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves2Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves2Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves2Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves3Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves3Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves3Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves4Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves4Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves4Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves6Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves6Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves6Objects3.length = 0;
gdjs.startCode.GDOrangeTreeLeaves5Objects1.length = 0;
gdjs.startCode.GDOrangeTreeLeaves5Objects2.length = 0;
gdjs.startCode.GDOrangeTreeLeaves5Objects3.length = 0;
gdjs.startCode.GDRedFlowerObjects1.length = 0;
gdjs.startCode.GDRedFlowerObjects2.length = 0;
gdjs.startCode.GDRedFlowerObjects3.length = 0;
gdjs.startCode.GDPurpleSmallPlantObjects1.length = 0;
gdjs.startCode.GDPurpleSmallPlantObjects2.length = 0;
gdjs.startCode.GDPurpleSmallPlantObjects3.length = 0;
gdjs.startCode.GDSmallGrassObjects1.length = 0;
gdjs.startCode.GDSmallGrassObjects2.length = 0;
gdjs.startCode.GDSmallGrassObjects3.length = 0;
gdjs.startCode.GDSmallPlant1Objects1.length = 0;
gdjs.startCode.GDSmallPlant1Objects2.length = 0;
gdjs.startCode.GDSmallPlant1Objects3.length = 0;
gdjs.startCode.GDTrunk1Objects1.length = 0;
gdjs.startCode.GDTrunk1Objects2.length = 0;
gdjs.startCode.GDTrunk1Objects3.length = 0;
gdjs.startCode.GDSmallPlant2Objects1.length = 0;
gdjs.startCode.GDSmallPlant2Objects2.length = 0;
gdjs.startCode.GDSmallPlant2Objects3.length = 0;
gdjs.startCode.GDTrunk4Objects1.length = 0;
gdjs.startCode.GDTrunk4Objects2.length = 0;
gdjs.startCode.GDTrunk4Objects3.length = 0;
gdjs.startCode.GDTinyGrassObjects1.length = 0;
gdjs.startCode.GDTinyGrassObjects2.length = 0;
gdjs.startCode.GDTinyGrassObjects3.length = 0;
gdjs.startCode.GDTrunk2Objects1.length = 0;
gdjs.startCode.GDTrunk2Objects2.length = 0;
gdjs.startCode.GDTrunk2Objects3.length = 0;
gdjs.startCode.GDTrunk3Objects1.length = 0;
gdjs.startCode.GDTrunk3Objects2.length = 0;
gdjs.startCode.GDTrunk3Objects3.length = 0;
gdjs.startCode.GDWhiteTree1Objects1.length = 0;
gdjs.startCode.GDWhiteTree1Objects2.length = 0;
gdjs.startCode.GDWhiteTree1Objects3.length = 0;
gdjs.startCode.GDWhiteTree2Objects1.length = 0;
gdjs.startCode.GDWhiteTree2Objects2.length = 0;
gdjs.startCode.GDWhiteTree2Objects3.length = 0;
gdjs.startCode.GDWhiteTree3Objects1.length = 0;
gdjs.startCode.GDWhiteTree3Objects2.length = 0;
gdjs.startCode.GDWhiteTree3Objects3.length = 0;
gdjs.startCode.GDWhiteTrunk3Objects1.length = 0;
gdjs.startCode.GDWhiteTrunk3Objects2.length = 0;
gdjs.startCode.GDWhiteTrunk3Objects3.length = 0;
gdjs.startCode.GDWhiteTrunk4Objects1.length = 0;
gdjs.startCode.GDWhiteTrunk4Objects2.length = 0;
gdjs.startCode.GDWhiteTrunk4Objects3.length = 0;
gdjs.startCode.GDWhiteTrunk2Objects1.length = 0;
gdjs.startCode.GDWhiteTrunk2Objects2.length = 0;
gdjs.startCode.GDWhiteTrunk2Objects3.length = 0;
gdjs.startCode.GDWhiteTrunkObjects1.length = 0;
gdjs.startCode.GDWhiteTrunkObjects2.length = 0;
gdjs.startCode.GDWhiteTrunkObjects3.length = 0;
gdjs.startCode.GDRock2Objects1.length = 0;
gdjs.startCode.GDRock2Objects2.length = 0;
gdjs.startCode.GDRock2Objects3.length = 0;
gdjs.startCode.GDRock1Objects1.length = 0;
gdjs.startCode.GDRock1Objects2.length = 0;
gdjs.startCode.GDRock1Objects3.length = 0;
gdjs.startCode.GDRock4Objects1.length = 0;
gdjs.startCode.GDRock4Objects2.length = 0;
gdjs.startCode.GDRock4Objects3.length = 0;
gdjs.startCode.GDRock3Objects1.length = 0;
gdjs.startCode.GDRock3Objects2.length = 0;
gdjs.startCode.GDRock3Objects3.length = 0;
gdjs.startCode.GDRock5Objects1.length = 0;
gdjs.startCode.GDRock5Objects2.length = 0;
gdjs.startCode.GDRock5Objects3.length = 0;
gdjs.startCode.GDRock6Objects1.length = 0;
gdjs.startCode.GDRock6Objects2.length = 0;
gdjs.startCode.GDRock6Objects3.length = 0;
gdjs.startCode.GDRockWithGrass2Objects1.length = 0;
gdjs.startCode.GDRockWithGrass2Objects2.length = 0;
gdjs.startCode.GDRockWithGrass2Objects3.length = 0;
gdjs.startCode.GDRockWithGrass3Objects1.length = 0;
gdjs.startCode.GDRockWithGrass3Objects2.length = 0;
gdjs.startCode.GDRockWithGrass3Objects3.length = 0;
gdjs.startCode.GDRockWithGrassObjects1.length = 0;
gdjs.startCode.GDRockWithGrassObjects2.length = 0;
gdjs.startCode.GDRockWithGrassObjects3.length = 0;
gdjs.startCode.GDVikingBoatObjects1.length = 0;
gdjs.startCode.GDVikingBoatObjects2.length = 0;
gdjs.startCode.GDVikingBoatObjects3.length = 0;
gdjs.startCode.GDLifeboatObjects1.length = 0;
gdjs.startCode.GDLifeboatObjects2.length = 0;
gdjs.startCode.GDLifeboatObjects3.length = 0;
gdjs.startCode.GDCruiseShipObjects1.length = 0;
gdjs.startCode.GDCruiseShipObjects2.length = 0;
gdjs.startCode.GDCruiseShipObjects3.length = 0;
gdjs.startCode.GDSailShipObjects1.length = 0;
gdjs.startCode.GDSailShipObjects2.length = 0;
gdjs.startCode.GDSailShipObjects3.length = 0;
gdjs.startCode.GDBoatWSailObjects1.length = 0;
gdjs.startCode.GDBoatWSailObjects2.length = 0;
gdjs.startCode.GDBoatWSailObjects3.length = 0;
gdjs.startCode.GDBoatObjects1.length = 0;
gdjs.startCode.GDBoatObjects2.length = 0;
gdjs.startCode.GDBoatObjects3.length = 0;
gdjs.startCode.GDNewSprite2Objects1.length = 0;
gdjs.startCode.GDNewSprite2Objects2.length = 0;
gdjs.startCode.GDNewSprite2Objects3.length = 0;
gdjs.startCode.GD_9595029Objects1.length = 0;
gdjs.startCode.GD_9595029Objects2.length = 0;
gdjs.startCode.GD_9595029Objects3.length = 0;
gdjs.startCode.GD_9595030Objects1.length = 0;
gdjs.startCode.GD_9595030Objects2.length = 0;
gdjs.startCode.GD_9595030Objects3.length = 0;
gdjs.startCode.GDStartButtonObjects1.length = 0;
gdjs.startCode.GDStartButtonObjects2.length = 0;
gdjs.startCode.GDStartButtonObjects3.length = 0;


return;

}

gdjs['startCode'] = gdjs.startCode;
