gdjs.satarCode = {};
gdjs.satarCode.localVariables = [];
gdjs.satarCode.GDOrangeLeavesObjects1= [];
gdjs.satarCode.GDOrangeLeavesObjects2= [];
gdjs.satarCode.GDBigGreenTree4Objects1= [];
gdjs.satarCode.GDBigGreenTree4Objects2= [];
gdjs.satarCode.GDGreenLeavesObjects1= [];
gdjs.satarCode.GDGreenLeavesObjects2= [];
gdjs.satarCode.GDBigGreenTree3Objects1= [];
gdjs.satarCode.GDBigGreenTree3Objects2= [];
gdjs.satarCode.GDBigGreenTree2Objects1= [];
gdjs.satarCode.GDBigGreenTree2Objects2= [];
gdjs.satarCode.GDBigGreenTree1Objects1= [];
gdjs.satarCode.GDBigGreenTree1Objects2= [];
gdjs.satarCode.GDBigGreenTree5Objects1= [];
gdjs.satarCode.GDBigGreenTree5Objects2= [];
gdjs.satarCode.GDBigGreenTree6Objects1= [];
gdjs.satarCode.GDBigGreenTree6Objects2= [];
gdjs.satarCode.GDBigGreenTree7Objects1= [];
gdjs.satarCode.GDBigGreenTree7Objects2= [];
gdjs.satarCode.GDBigOrangeTree1Objects1= [];
gdjs.satarCode.GDBigOrangeTree1Objects2= [];
gdjs.satarCode.GDBigGreenTree8Objects1= [];
gdjs.satarCode.GDBigGreenTree8Objects2= [];
gdjs.satarCode.GDBigOrangeTree2Objects1= [];
gdjs.satarCode.GDBigOrangeTree2Objects2= [];
gdjs.satarCode.GDBigOrangeTree5Objects1= [];
gdjs.satarCode.GDBigOrangeTree5Objects2= [];
gdjs.satarCode.GDBigOrangeTree4Objects1= [];
gdjs.satarCode.GDBigOrangeTree4Objects2= [];
gdjs.satarCode.GDBigOrangeTree3Objects1= [];
gdjs.satarCode.GDBigOrangeTree3Objects2= [];
gdjs.satarCode.GDBigTreeWithSnow1Objects1= [];
gdjs.satarCode.GDBigTreeWithSnow1Objects2= [];
gdjs.satarCode.GDBigOrangeTree6Objects1= [];
gdjs.satarCode.GDBigOrangeTree6Objects2= [];
gdjs.satarCode.GDBigTreeWithSnow2Objects1= [];
gdjs.satarCode.GDBigTreeWithSnow2Objects2= [];
gdjs.satarCode.GDBlueSmallPlantObjects1= [];
gdjs.satarCode.GDBlueSmallPlantObjects2= [];
gdjs.satarCode.GDBlueFlowerObjects1= [];
gdjs.satarCode.GDBlueFlowerObjects2= [];
gdjs.satarCode.GDGreenBush3Objects1= [];
gdjs.satarCode.GDGreenBush3Objects2= [];
gdjs.satarCode.GDBigTreeWithSnow3Objects1= [];
gdjs.satarCode.GDBigTreeWithSnow3Objects2= [];
gdjs.satarCode.GDGreenTreeLeaves1Objects1= [];
gdjs.satarCode.GDGreenTreeLeaves1Objects2= [];
gdjs.satarCode.GDGreenBush2Objects1= [];
gdjs.satarCode.GDGreenBush2Objects2= [];
gdjs.satarCode.GDGreenBush4Objects1= [];
gdjs.satarCode.GDGreenBush4Objects2= [];
gdjs.satarCode.GDGreenBush1Objects1= [];
gdjs.satarCode.GDGreenBush1Objects2= [];
gdjs.satarCode.GDGreenTreeLeaves2Objects1= [];
gdjs.satarCode.GDGreenTreeLeaves2Objects2= [];
gdjs.satarCode.GDGreenTreeLeaves4Objects1= [];
gdjs.satarCode.GDGreenTreeLeaves4Objects2= [];
gdjs.satarCode.GDGreenTreeLeaves5Objects1= [];
gdjs.satarCode.GDGreenTreeLeaves5Objects2= [];
gdjs.satarCode.GDGreenTreeLeaves3Objects1= [];
gdjs.satarCode.GDGreenTreeLeaves3Objects2= [];
gdjs.satarCode.GDGreenTreeLeaves6Objects1= [];
gdjs.satarCode.GDGreenTreeLeaves6Objects2= [];
gdjs.satarCode.GDGreenTreeLeaves7Objects1= [];
gdjs.satarCode.GDGreenTreeLeaves7Objects2= [];
gdjs.satarCode.GDOrangeTreeLeaves1Objects1= [];
gdjs.satarCode.GDOrangeTreeLeaves1Objects2= [];
gdjs.satarCode.GDOrangeTreeLeaves2Objects1= [];
gdjs.satarCode.GDOrangeTreeLeaves2Objects2= [];
gdjs.satarCode.GDOrangeTreeLeaves5Objects1= [];
gdjs.satarCode.GDOrangeTreeLeaves5Objects2= [];
gdjs.satarCode.GDOrangeTreeLeaves6Objects1= [];
gdjs.satarCode.GDOrangeTreeLeaves6Objects2= [];
gdjs.satarCode.GDOrangeTreeLeaves3Objects1= [];
gdjs.satarCode.GDOrangeTreeLeaves3Objects2= [];
gdjs.satarCode.GDOrangeTreeLeaves4Objects1= [];
gdjs.satarCode.GDOrangeTreeLeaves4Objects2= [];
gdjs.satarCode.GDPurpleSmallPlantObjects1= [];
gdjs.satarCode.GDPurpleSmallPlantObjects2= [];
gdjs.satarCode.GDRedFlowerObjects1= [];
gdjs.satarCode.GDRedFlowerObjects2= [];
gdjs.satarCode.GDSmallGrassObjects1= [];
gdjs.satarCode.GDSmallGrassObjects2= [];
gdjs.satarCode.GDTrunk1Objects1= [];
gdjs.satarCode.GDTrunk1Objects2= [];
gdjs.satarCode.GDSmallPlant1Objects1= [];
gdjs.satarCode.GDSmallPlant1Objects2= [];
gdjs.satarCode.GDTinyGrassObjects1= [];
gdjs.satarCode.GDTinyGrassObjects2= [];
gdjs.satarCode.GDTrunk2Objects1= [];
gdjs.satarCode.GDTrunk2Objects2= [];
gdjs.satarCode.GDSmallPlant2Objects1= [];
gdjs.satarCode.GDSmallPlant2Objects2= [];
gdjs.satarCode.GDTrunk3Objects1= [];
gdjs.satarCode.GDTrunk3Objects2= [];
gdjs.satarCode.GDTrunk4Objects1= [];
gdjs.satarCode.GDTrunk4Objects2= [];
gdjs.satarCode.GDWhiteTree1Objects1= [];
gdjs.satarCode.GDWhiteTree1Objects2= [];
gdjs.satarCode.GDWhiteTrunk2Objects1= [];
gdjs.satarCode.GDWhiteTrunk2Objects2= [];
gdjs.satarCode.GDWhiteTree2Objects1= [];
gdjs.satarCode.GDWhiteTree2Objects2= [];
gdjs.satarCode.GDWhiteTree3Objects1= [];
gdjs.satarCode.GDWhiteTree3Objects2= [];
gdjs.satarCode.GDWhiteTrunk3Objects1= [];
gdjs.satarCode.GDWhiteTrunk3Objects2= [];
gdjs.satarCode.GDWhiteTrunk4Objects1= [];
gdjs.satarCode.GDWhiteTrunk4Objects2= [];
gdjs.satarCode.GDWhiteTrunkObjects1= [];
gdjs.satarCode.GDWhiteTrunkObjects2= [];
gdjs.satarCode.GDRock1Objects1= [];
gdjs.satarCode.GDRock1Objects2= [];
gdjs.satarCode.GDRock2Objects1= [];
gdjs.satarCode.GDRock2Objects2= [];
gdjs.satarCode.GDRock4Objects1= [];
gdjs.satarCode.GDRock4Objects2= [];
gdjs.satarCode.GDRock3Objects1= [];
gdjs.satarCode.GDRock3Objects2= [];
gdjs.satarCode.GDRock6Objects1= [];
gdjs.satarCode.GDRock6Objects2= [];
gdjs.satarCode.GDRock5Objects1= [];
gdjs.satarCode.GDRock5Objects2= [];
gdjs.satarCode.GDRockWithGrass2Objects1= [];
gdjs.satarCode.GDRockWithGrass2Objects2= [];
gdjs.satarCode.GDRockWithGrass3Objects1= [];
gdjs.satarCode.GDRockWithGrass3Objects2= [];
gdjs.satarCode.GDNewSprite2Objects1= [];
gdjs.satarCode.GDNewSprite2Objects2= [];
gdjs.satarCode.GDStarObjects1= [];
gdjs.satarCode.GDStarObjects2= [];
gdjs.satarCode.GDDevilShooterObjects1= [];
gdjs.satarCode.GDDevilShooterObjects2= [];


gdjs.satarCode.eventsList0 = function(runtimeScene) {

{

gdjs.copyArray(runtimeScene.getObjects("Star"), gdjs.satarCode.GDStarObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.satarCode.GDStarObjects1.length;i<l;++i) {
    if ( gdjs.satarCode.GDStarObjects1[i].getBehavior("ButtonFSM").IsClicked((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined)) ) {
        isConditionTrue_0 = true;
        gdjs.satarCode.GDStarObjects1[k] = gdjs.satarCode.GDStarObjects1[i];
        ++k;
    }
}
gdjs.satarCode.GDStarObjects1.length = k;
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "level1", false);
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("Star"), gdjs.satarCode.GDStarObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.satarCode.GDStarObjects1.length;i<l;++i) {
    if ( gdjs.satarCode.GDStarObjects1[i].getBehavior("ButtonFSM").IsHovered((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined)) ) {
        isConditionTrue_0 = true;
        gdjs.satarCode.GDStarObjects1[k] = gdjs.satarCode.GDStarObjects1[i];
        ++k;
    }
}
gdjs.satarCode.GDStarObjects1.length = k;
if (isConditionTrue_0) {
isConditionTrue_0 = false;
{isConditionTrue_0 = runtimeScene.getOnceTriggers().triggerOnce(15638852);
}
}
if (isConditionTrue_0) {
{gdjs.evtTools.sound.playSound(runtimeScene, "923517cfc7f1500e851f0bbcdd357fe2b982745b128fcb3acc40d1a229575882_Click_02.aac", false, 100, 1);
}}

}


};

gdjs.satarCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.satarCode.GDOrangeLeavesObjects1.length = 0;
gdjs.satarCode.GDOrangeLeavesObjects2.length = 0;
gdjs.satarCode.GDBigGreenTree4Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree4Objects2.length = 0;
gdjs.satarCode.GDGreenLeavesObjects1.length = 0;
gdjs.satarCode.GDGreenLeavesObjects2.length = 0;
gdjs.satarCode.GDBigGreenTree3Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree3Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree2Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree2Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree1Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree1Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree5Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree5Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree6Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree6Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree7Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree7Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree1Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree1Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree8Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree8Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree2Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree2Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree5Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree5Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree4Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree4Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree3Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree3Objects2.length = 0;
gdjs.satarCode.GDBigTreeWithSnow1Objects1.length = 0;
gdjs.satarCode.GDBigTreeWithSnow1Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree6Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree6Objects2.length = 0;
gdjs.satarCode.GDBigTreeWithSnow2Objects1.length = 0;
gdjs.satarCode.GDBigTreeWithSnow2Objects2.length = 0;
gdjs.satarCode.GDBlueSmallPlantObjects1.length = 0;
gdjs.satarCode.GDBlueSmallPlantObjects2.length = 0;
gdjs.satarCode.GDBlueFlowerObjects1.length = 0;
gdjs.satarCode.GDBlueFlowerObjects2.length = 0;
gdjs.satarCode.GDGreenBush3Objects1.length = 0;
gdjs.satarCode.GDGreenBush3Objects2.length = 0;
gdjs.satarCode.GDBigTreeWithSnow3Objects1.length = 0;
gdjs.satarCode.GDBigTreeWithSnow3Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves1Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves1Objects2.length = 0;
gdjs.satarCode.GDGreenBush2Objects1.length = 0;
gdjs.satarCode.GDGreenBush2Objects2.length = 0;
gdjs.satarCode.GDGreenBush4Objects1.length = 0;
gdjs.satarCode.GDGreenBush4Objects2.length = 0;
gdjs.satarCode.GDGreenBush1Objects1.length = 0;
gdjs.satarCode.GDGreenBush1Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves2Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves2Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves4Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves4Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves5Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves5Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves3Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves3Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves6Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves6Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves7Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves7Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves1Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves1Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves2Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves2Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves5Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves5Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves6Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves6Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves3Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves3Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves4Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves4Objects2.length = 0;
gdjs.satarCode.GDPurpleSmallPlantObjects1.length = 0;
gdjs.satarCode.GDPurpleSmallPlantObjects2.length = 0;
gdjs.satarCode.GDRedFlowerObjects1.length = 0;
gdjs.satarCode.GDRedFlowerObjects2.length = 0;
gdjs.satarCode.GDSmallGrassObjects1.length = 0;
gdjs.satarCode.GDSmallGrassObjects2.length = 0;
gdjs.satarCode.GDTrunk1Objects1.length = 0;
gdjs.satarCode.GDTrunk1Objects2.length = 0;
gdjs.satarCode.GDSmallPlant1Objects1.length = 0;
gdjs.satarCode.GDSmallPlant1Objects2.length = 0;
gdjs.satarCode.GDTinyGrassObjects1.length = 0;
gdjs.satarCode.GDTinyGrassObjects2.length = 0;
gdjs.satarCode.GDTrunk2Objects1.length = 0;
gdjs.satarCode.GDTrunk2Objects2.length = 0;
gdjs.satarCode.GDSmallPlant2Objects1.length = 0;
gdjs.satarCode.GDSmallPlant2Objects2.length = 0;
gdjs.satarCode.GDTrunk3Objects1.length = 0;
gdjs.satarCode.GDTrunk3Objects2.length = 0;
gdjs.satarCode.GDTrunk4Objects1.length = 0;
gdjs.satarCode.GDTrunk4Objects2.length = 0;
gdjs.satarCode.GDWhiteTree1Objects1.length = 0;
gdjs.satarCode.GDWhiteTree1Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunk2Objects1.length = 0;
gdjs.satarCode.GDWhiteTrunk2Objects2.length = 0;
gdjs.satarCode.GDWhiteTree2Objects1.length = 0;
gdjs.satarCode.GDWhiteTree2Objects2.length = 0;
gdjs.satarCode.GDWhiteTree3Objects1.length = 0;
gdjs.satarCode.GDWhiteTree3Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunk3Objects1.length = 0;
gdjs.satarCode.GDWhiteTrunk3Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunk4Objects1.length = 0;
gdjs.satarCode.GDWhiteTrunk4Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunkObjects1.length = 0;
gdjs.satarCode.GDWhiteTrunkObjects2.length = 0;
gdjs.satarCode.GDRock1Objects1.length = 0;
gdjs.satarCode.GDRock1Objects2.length = 0;
gdjs.satarCode.GDRock2Objects1.length = 0;
gdjs.satarCode.GDRock2Objects2.length = 0;
gdjs.satarCode.GDRock4Objects1.length = 0;
gdjs.satarCode.GDRock4Objects2.length = 0;
gdjs.satarCode.GDRock3Objects1.length = 0;
gdjs.satarCode.GDRock3Objects2.length = 0;
gdjs.satarCode.GDRock6Objects1.length = 0;
gdjs.satarCode.GDRock6Objects2.length = 0;
gdjs.satarCode.GDRock5Objects1.length = 0;
gdjs.satarCode.GDRock5Objects2.length = 0;
gdjs.satarCode.GDRockWithGrass2Objects1.length = 0;
gdjs.satarCode.GDRockWithGrass2Objects2.length = 0;
gdjs.satarCode.GDRockWithGrass3Objects1.length = 0;
gdjs.satarCode.GDRockWithGrass3Objects2.length = 0;
gdjs.satarCode.GDNewSprite2Objects1.length = 0;
gdjs.satarCode.GDNewSprite2Objects2.length = 0;
gdjs.satarCode.GDStarObjects1.length = 0;
gdjs.satarCode.GDStarObjects2.length = 0;
gdjs.satarCode.GDDevilShooterObjects1.length = 0;
gdjs.satarCode.GDDevilShooterObjects2.length = 0;

gdjs.satarCode.eventsList0(runtimeScene);
gdjs.satarCode.GDOrangeLeavesObjects1.length = 0;
gdjs.satarCode.GDOrangeLeavesObjects2.length = 0;
gdjs.satarCode.GDBigGreenTree4Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree4Objects2.length = 0;
gdjs.satarCode.GDGreenLeavesObjects1.length = 0;
gdjs.satarCode.GDGreenLeavesObjects2.length = 0;
gdjs.satarCode.GDBigGreenTree3Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree3Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree2Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree2Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree1Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree1Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree5Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree5Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree6Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree6Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree7Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree7Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree1Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree1Objects2.length = 0;
gdjs.satarCode.GDBigGreenTree8Objects1.length = 0;
gdjs.satarCode.GDBigGreenTree8Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree2Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree2Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree5Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree5Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree4Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree4Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree3Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree3Objects2.length = 0;
gdjs.satarCode.GDBigTreeWithSnow1Objects1.length = 0;
gdjs.satarCode.GDBigTreeWithSnow1Objects2.length = 0;
gdjs.satarCode.GDBigOrangeTree6Objects1.length = 0;
gdjs.satarCode.GDBigOrangeTree6Objects2.length = 0;
gdjs.satarCode.GDBigTreeWithSnow2Objects1.length = 0;
gdjs.satarCode.GDBigTreeWithSnow2Objects2.length = 0;
gdjs.satarCode.GDBlueSmallPlantObjects1.length = 0;
gdjs.satarCode.GDBlueSmallPlantObjects2.length = 0;
gdjs.satarCode.GDBlueFlowerObjects1.length = 0;
gdjs.satarCode.GDBlueFlowerObjects2.length = 0;
gdjs.satarCode.GDGreenBush3Objects1.length = 0;
gdjs.satarCode.GDGreenBush3Objects2.length = 0;
gdjs.satarCode.GDBigTreeWithSnow3Objects1.length = 0;
gdjs.satarCode.GDBigTreeWithSnow3Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves1Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves1Objects2.length = 0;
gdjs.satarCode.GDGreenBush2Objects1.length = 0;
gdjs.satarCode.GDGreenBush2Objects2.length = 0;
gdjs.satarCode.GDGreenBush4Objects1.length = 0;
gdjs.satarCode.GDGreenBush4Objects2.length = 0;
gdjs.satarCode.GDGreenBush1Objects1.length = 0;
gdjs.satarCode.GDGreenBush1Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves2Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves2Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves4Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves4Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves5Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves5Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves3Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves3Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves6Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves6Objects2.length = 0;
gdjs.satarCode.GDGreenTreeLeaves7Objects1.length = 0;
gdjs.satarCode.GDGreenTreeLeaves7Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves1Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves1Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves2Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves2Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves5Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves5Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves6Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves6Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves3Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves3Objects2.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves4Objects1.length = 0;
gdjs.satarCode.GDOrangeTreeLeaves4Objects2.length = 0;
gdjs.satarCode.GDPurpleSmallPlantObjects1.length = 0;
gdjs.satarCode.GDPurpleSmallPlantObjects2.length = 0;
gdjs.satarCode.GDRedFlowerObjects1.length = 0;
gdjs.satarCode.GDRedFlowerObjects2.length = 0;
gdjs.satarCode.GDSmallGrassObjects1.length = 0;
gdjs.satarCode.GDSmallGrassObjects2.length = 0;
gdjs.satarCode.GDTrunk1Objects1.length = 0;
gdjs.satarCode.GDTrunk1Objects2.length = 0;
gdjs.satarCode.GDSmallPlant1Objects1.length = 0;
gdjs.satarCode.GDSmallPlant1Objects2.length = 0;
gdjs.satarCode.GDTinyGrassObjects1.length = 0;
gdjs.satarCode.GDTinyGrassObjects2.length = 0;
gdjs.satarCode.GDTrunk2Objects1.length = 0;
gdjs.satarCode.GDTrunk2Objects2.length = 0;
gdjs.satarCode.GDSmallPlant2Objects1.length = 0;
gdjs.satarCode.GDSmallPlant2Objects2.length = 0;
gdjs.satarCode.GDTrunk3Objects1.length = 0;
gdjs.satarCode.GDTrunk3Objects2.length = 0;
gdjs.satarCode.GDTrunk4Objects1.length = 0;
gdjs.satarCode.GDTrunk4Objects2.length = 0;
gdjs.satarCode.GDWhiteTree1Objects1.length = 0;
gdjs.satarCode.GDWhiteTree1Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunk2Objects1.length = 0;
gdjs.satarCode.GDWhiteTrunk2Objects2.length = 0;
gdjs.satarCode.GDWhiteTree2Objects1.length = 0;
gdjs.satarCode.GDWhiteTree2Objects2.length = 0;
gdjs.satarCode.GDWhiteTree3Objects1.length = 0;
gdjs.satarCode.GDWhiteTree3Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunk3Objects1.length = 0;
gdjs.satarCode.GDWhiteTrunk3Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunk4Objects1.length = 0;
gdjs.satarCode.GDWhiteTrunk4Objects2.length = 0;
gdjs.satarCode.GDWhiteTrunkObjects1.length = 0;
gdjs.satarCode.GDWhiteTrunkObjects2.length = 0;
gdjs.satarCode.GDRock1Objects1.length = 0;
gdjs.satarCode.GDRock1Objects2.length = 0;
gdjs.satarCode.GDRock2Objects1.length = 0;
gdjs.satarCode.GDRock2Objects2.length = 0;
gdjs.satarCode.GDRock4Objects1.length = 0;
gdjs.satarCode.GDRock4Objects2.length = 0;
gdjs.satarCode.GDRock3Objects1.length = 0;
gdjs.satarCode.GDRock3Objects2.length = 0;
gdjs.satarCode.GDRock6Objects1.length = 0;
gdjs.satarCode.GDRock6Objects2.length = 0;
gdjs.satarCode.GDRock5Objects1.length = 0;
gdjs.satarCode.GDRock5Objects2.length = 0;
gdjs.satarCode.GDRockWithGrass2Objects1.length = 0;
gdjs.satarCode.GDRockWithGrass2Objects2.length = 0;
gdjs.satarCode.GDRockWithGrass3Objects1.length = 0;
gdjs.satarCode.GDRockWithGrass3Objects2.length = 0;
gdjs.satarCode.GDNewSprite2Objects1.length = 0;
gdjs.satarCode.GDNewSprite2Objects2.length = 0;
gdjs.satarCode.GDStarObjects1.length = 0;
gdjs.satarCode.GDStarObjects2.length = 0;
gdjs.satarCode.GDDevilShooterObjects1.length = 0;
gdjs.satarCode.GDDevilShooterObjects2.length = 0;


return;

}

gdjs['satarCode'] = gdjs.satarCode;
